### ISSUE TITLE
Consider adding Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [societe-generale/rabbitmq-advanced-spring-boot-starter#11]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

We are reviewing our [community starters list](https://github.com/spring-projects/spring-boot/blob/7683d346e31bbe0313a03ce487ee59454665a143/spring-boot-project/spring-boot-starters/README.adoc) and a quick look here suggests that this starter doesn’t yet support Spring Boot 2.

Can you please let us know if/when you plan to support Spring Boot 2?

Thanks!

**Comment by vincent-fuchs** [comment]
yes, we're planning to make it compatible - give us a few weeks, plate is quite full right now  ;-)

**Comment by vincent-fuchs** [comment]
@anandmnair , can we close this ? or do you need a few days to perform tests and confirm ?

**Comment by anandmnair** [comment]
Yes. 
I have made the release 2.0.0.RELEASE

    <dependency>
        <groupId>com.societegenerale</groupId>
        <artifactId>rabbitmq-advanced-spring-boot-starter</artifactId>
        <version>2.0.0.RELEASE</version>
        
    </dependency>

**Comment by anandmnair** [comment]
New Release is made 2.0.0.RELEASE with the requested spring boot 2.x.x upgradation. Hence closing the issue

**Comment by snicoll** [comment]
I've also restored the starter reference in our third party list: https://github.com/spring-projects/spring-boot/commit/ff11166af8c0679d13f80d1a1f8eb2e9db47c8ae
