### ISSUE TITLE
these help me resolve a problem

### ISSUE THREAD

**Issue by forgeekscn** [societe-generale/rabbitmq-advanced-spring-boot-starter#17]
## Type of Issue

It is a : 
 - [ ] bug
 - [ ] request
 - [ ] question regarding the documentation

## Current Behavior

~~~
~~~

## Expected Behavior

~~~
~~~

## Your Environment

* Version used:
* OS and version:
* Version of libs used:

**Comment by vincent-fuchs** [comment]
happy it was useful !
